/* eslint-env node */
// eslint-disable-next-line @typescript-eslint/no-var-requires
const colors = require("tailwindcss/colors");

module.exports = {
  content: [
    "./src/**/*.html",
    "./src/**/*.md",
    "./src/**/*.mdx",
    "./src/**/*.jsx",
    "./src/**/*.js",
    "./src/**/*.tsx",
    "./src/**/*.ts",
  ],
  theme: {
    extend: {},
    colors: colors,
  },
  variants: {
    extend: {
      opacity: [
        "responsive",
        "group-hover",
        "focus-within",
        "hover",
        "focus",
        "motion-safe",
      ],
      animation: ["motion-safe"],
      borderWidth: ["hover"],
      borderStyle: ["hover", "focus"],
      borderRadius: ["hover"],
      translate: ["direction"],
    },
  },
  plugins: [
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    require("tailwindcss-dir")(),
  ],
  purge: {
    safelist: [
      // These are dynamically generated by the <TreeView> component,
      // depending on the nesting level:
      "pl-0",
      "pl-1",
      "pl-2",
      "pl-3",
      "pl-4",
      "pl-5",
      "pl-6",
      "pl-7",
      "pl-8",
      "pl-9",
      "pl-10",
      "pl-11",
      "pl-11",
    ],
  },
};
